#autogenerated by sqlautocode

from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relation

engine = create_engine('sqlite:///database.sqlite3')
DeclarativeBase = declarative_base()
metadata = DeclarativeBase.metadata
metadata.bind = engine

class OmsStatLoad(DeclarativeBase):
    __tablename__ = 'oms_stat_load'

    __table_args__ = {}

    #column definitions
    avg_1 = Column(u'avg_1', VARCHAR(length=8), nullable=False)
    avg_15 = Column(u'avg_15', VARCHAR(length=8), nullable=False)
    avg_5 = Column(u'avg_5', VARCHAR(length=8), nullable=False)
    check_time = Column(u'check_time', VARCHAR(length=19), primary_key=True, nullable=False)
    host_name = Column(u'host_name', VARCHAR(length=64), primary_key=True, nullable=False)

    #relation definitions


class OmsStatTraffic(DeclarativeBase):
    __tablename__ = 'oms_stat_traffic'

    __table_args__ = {}

    #column definitions
    check_time = Column(u'check_time', VARCHAR(length=19), primary_key=True, nullable=False)
    host_name = Column(u'host_name', VARCHAR(length=64), primary_key=True, nullable=False)
    traffic = Column(u'traffic', INTEGER(), nullable=False)

    #relation definitions


