#!/bin/sh
# toughnms stable install script
# author: jamiesun.net@gmail.com

rundir=/home/toughrun

usage ()
{
    cat <<EOF
    Usage: $0 [OPTIONS] instance

    docker_setup                install docker, docker-compose
    pull                        toughnms docker images pull
    install                     install toughnms with already exists mysql
    remove                      uninstall toughnms
    config                      toughnms instance config edit
    status                      toughnms instance status
    restart                     toughnms instance restart
    stop                        toughnms instance stop
    upgrade                     toughnms instance stable version upgrade
    upgrade_dev                 toughnms instance develop version upgrade
    logs                        toughnms instance logs
    dsh                         toughnms instance bash term

    All other options are passed to the toughrad program.
EOF
        exit 1
}


install()
{
    instance=${1:-toughnms}

    mkdir -p ${rundir}/$instance

    read -p "version [stable,dev](stable): " tn_release
    tn_release=${tn_release:-stable}

    read -p "toughnms web port [8099]: " web_port
    web_port=${web_port:-8099}

    cat <<EOF

    toughnms instance config (with sqlite):

    instance name: $instance
    web_port: ${web_port}

EOF

    rm -f ${rundir}/$instance/docker-compose.yml
    cat > ${rundir}/$instance/docker-compose.yml  <<EOF
radius:
    container_name: radius_${instance}
    image: "index.alauda.cn/toughstruct/toughnms:${tn_release}"
    ports:
        - "${web_port}:1816"
    restart: always
    ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
    volumes:
        - ${rundir}/$instance:/var/toughnms
EOF

    cd ${rundir}/$instance

    cat ${rundir}/$instance/docker-compose.yml

    docker-compose up -d

    docker-compose ps

    exit 0
}


docker_setup()
{
    curl -sSL https://get.daocloud.io/docker | sh

    curl -L https://get.daocloud.io/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose

    ln -s /usr/local/bin/docker-compose /usr/local/bin/docp

    service docker start
}


remove()
{
    instance=${1:-toughnms}

    cd ${rundir}/$instance
    read -p "Will delete all, do you confirm? [y/n](n): " is_rm
    is_rm=${is_rm:-n}
    if [ $is_rm == "y" ]; then
        docker-compose kill
        docker-compose rm
        rm -f ${rundir}/$instance/.install
    fi 
}


config()
{
    instance=${1:-toughnms}    
    vi ${rundir}/$instance/docker-compose.yml
}

status()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker-compose ps
}

restart()
{
    instance=${1:-toughnms}      
    cd ${rundir}/$instance
    docker-compose restart $2
    docker-compose ps
}

stop()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker-compose stop $2
    docker-compose ps
}

upgrade()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker exec -it radius_$instance /usr/local/bin/toughrun upgrade
    docker-compose restart
    docker-compose ps
}

upgrade_dev()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker exec -it radius_$instance /usr/local/bin/toughrun upgrade_dev
    docker-compose restart
    docker-compose ps
}


uplib()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker exec -it radius_$instance /usr/local/bin/toughrun uplib
    docker-compose restart 
    docker-compose ps
}

logs()
{
    instance=${1:-toughnms}
    cd ${rundir}/$instance
    echo "-------- nagios log -----------"
    tail -n 100 ./nagios.log
    echo "-------- mongodb log -----------"
    tail -n 100 ./mongodb.log
    echo "-------- toughnms log -----------"
    tail -f ./toughnms.log
}

dsh()
{
    instance=${1:-toughnms}    
    cd ${rundir}/$instance
    docker exec -it radius_$instance bash
}


pull()
{
    docker pull index.alauda.cn/toughstruct/toughnms:stable
    docker pull index.alauda.cn/toughstruct/toughnms:dev
}

update_shell()
{
    wget  https://raw.githubusercontent.com/talkincode/ToughNMS/master/scripts/tnshell  -O /usr/local/bin/tnshell
    chmod +x /usr/local/bin/trshell
}


case "$1" in

  docker_setup)
    docker_setup
  ;;

  install)
    install $2
  ;;

  install_with_lmysql)
    install_with_lmysql $2
  ;;

  install_with_rmysql)
    install_with_rmysql $2
  ;;

  remove)
    remove $2
  ;;

  config)
    config $2
  ;;

  status)
    status $2
  ;;

  restart)
    restart $2 $3
  ;;

  stop)
    stop $2 $3
  ;;

  logs)
    logs $2
  ;;

  dsh)
    dsh $2
  ;;

  pull)
    pull
  ;;

  upgrade)
    upgrade $2
  ;;

  upgrade_dev)
    upgrade_dev $2
  ;;

  uplib)
    uplib $2
  ;;

  update_shell)
    update_shell
  ;;


  *)
   usage
  ;;

esac