#!/bin/sh
# toughnms docker install script
# author: jamiesun.net@gmail.com
# version: 0.0.1

set -e

install()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps

    git clone -b stable https://github.com/talkincode/ToughNMS.git /opt/toughnms

    cp /opt/toughnms/etc/toughnms.json /etc/toughnms.json
    cp /opt/toughnms/etc/supervisord.conf /etc/supervisord.conf

    chmod +x /opt/toughnms/toughctl

    \cp /opt/toughnms/scripts/sendmail /usr/local/bin/sendmail
    \cp /opt/toughnms/scripts/perfstore /usr/local/bin/perfstore
    chmod +x /usr/local/bin/sendmail
    chmod +x /usr/local/bin/perfstore

    echo "test" > /var/toughnms/token
    echo "" > /usr/local/nagios/etc/objects/hostgroups.cfg
    /bin/cp /opt/toughnms/etc/nagios.cfg /usr/local/nagios/etc/nagios.cfg
    /bin/cp /opt/toughnms/etc/commands.cfg /usr/local/nagios/etc/objects/commands.cfg
    /bin/cp /opt/toughnms/etc/contacts.cfg /usr/local/nagios/etc/objects/contacts.cfg
    /bin/cp /opt/toughnms/etc/templates.cfg /usr/local/nagios/etc/objects/templates.cfg
    /bin/cp /opt/toughnms/etc/localhost.cfg /usr/local/nagios/etc/objects/localhost.cfg
}

initserv()
{
    if [ ! -f "/var/toughnms/data" ];then
        mkdir -p /var/toughnms/data
    fi

    if [ ! -f "/var/toughnms/data/mdb" ];then
        mkdir -p /var/toughnms/data/mdb
    fi

    if [ ! -f "/var/toughnms/.install" ];then
        pypy /opt/toughnms/toughctl --initdb
        echo "ok" > /var/toughnms/.install
        echo "init database ok!"
    fi

    echo "init service ok!"
}

manage()
{
    initserv
    pypy /opt/toughnms/toughctl --manage
}

mongodb()
{
    if [ ! -f "/var/toughnms/data/mdb" ];then
        mkdir -p /var/toughnms/data/mdb
    fi
    mongod --dbpath /var/toughnms/data/mdb
}

upgrade()
{
    cd /opt/toughnms
    git fetch origin stable
    git reset --hard FETCH_HEAD
    git clean -df
}

upgrade_dev()
{
    cd /opt/toughnms
    git fetch origin master
    git reset --hard FETCH_HEAD
    git clean -df
}


uplib()
{
    pypy -m pip install https://github.com/talkincode/toughlib/archive/master.zip --upgrade --no-deps
}

case "$1" in

  install)
    install
  ;;

  initserv)
    initserv
  ;;


  manage)
    manage
  ;;


  mongodb)
    mongodb
  ;;

  upgrade)
    upgrade
  ;;

  upgrade_dev)
    upgrade_dev
  ;;

  uplib)
    uplib
  ;;

esac

